### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by SuperHero2010** [wmw-modding/wheres-my-editor#4]
It turned out to be "cmd". I have finished downloading.

**Comment by SuperHero2010** [comment]
What should I do next?

**Comment by ego-lay-atman-bay** [comment]
I don't know what you have done already.

**Comment by SuperHero2010** [comment]
I haven't entered any commands yet.

**Comment by SuperHero2010** [comment]
If I enter miscellaneous commands, it may cause an error.

**Comment by SuperHero2010** [comment]
What command do I need to enter first to start the EXE file creation program?

**Comment by ego-lay-atman-bay** [comment]
It's all in the readme under "Building".

**Comment by SuperHero2010** [comment]
I try it.

**Comment by SuperHero2010** [comment]
Um... Is it necessary to download "requirements.txt", "requirements-build.txt", "build.py"?

**Comment by ego-lay-atman-bay** [comment]
It's necessary to download every single file. The `requirements.txt` file contains all the other packages that are needed to run the program, `requirements-build.txt` contains all the packages that are needed to build the exe, and `build.py` is needed to build the exe. All the files in the `src` folder are the program, which is what you would be editing.

The easiest way to download all the files is install GitHub Desktop, then on the main (code) page, click on the green "Code" button, and then click "Open with GitHub Desktop". 

Since it seems like you've never used python before, I suggest you instead do something a little easier than try to work on wme (since the code can be a little daunting to edit without any understanding of python). I'd suggest creating your own project to learn python, and then when you understand it, come back to wme and try to edit my code. Oh, and by the way, google (or whatever search engine you use) is your friend, that's how I learned python.

**Comment by SuperHero2010** [comment]
I can't edit your EXE code. But can I open WME with "Python"?

**Comment by ego-lay-atman-bay** [comment]
Yes. Python is the programming language that wme is written in. If you're going to be editing wme, you have to be able to understand pythpn. Trying to edit the exe will be much much more difficult.

**Comment by SuperHero2010** [comment]
But how?

**Comment by ego-lay-atman-bay** [comment]
Maybe try searching "How to run python program"

**Comment by SuperHero2010** [comment]
Perhaps the ">>>" line must display "windows@windows:" to be able to edit your application.

**Comment by SuperHero2010** [comment]
I have downloaded all your files.

**Comment by ego-lay-atman-bay** [comment]
No...? Where did you get that from?

I'm sorry, but it's honestly pretty difficult to help you if you don't know what you're doing. I don't have time to guide you every single step of the way. You're best bet is to find some youtube tutorial and learn python from a blank file, not wme.

**Comment by SuperHero2010** [comment]
Why are you so forgetful and slow to understand? Am I forcing you to give me step-by-step instructions? I downloaded all your files from "wmw-modding/wheres-my-editor" using "GitHub Desktop".

**Comment by SuperHero2010** [comment]
If there's no time, that's okay.

**Comment by ego-lay-atman-bay** [comment]
Why are you slow to understand? If you're going to be editing wme, you need to know python, and judging by the fact that you asked where to get python, and you didn't know what `requirements.txt` was, I think it's safe to say you don't know how to code in python, and you're probably not gonna understand anything in the wme code. You're much better off learning python from a youtube tutorial than trying to edit wme. Plus, a lot of the code you need to edit is in wmwpy, which you'd also need to understand how to edit, and set up an environment to allow you to test your edits.

Not to mention, I've told you where to find the instructions on how to build wme, they're [RIGHT HERE](https://github.com/wmw-modding/wheres-my-editor?tab=readme-ov-file#building)! I shouldn't need to tell you what to do next. If you don't know what to do, try googling it.

**Comment by SuperHero2010** [comment]
This is the second time you're slow to understand.

**Comment by SuperHero2010** [comment]
I'm busy.

**Comment by ego-lay-atman-bay** [comment]
I'm just gonna lock this since you clearly don't understand anything I'm saying.

**Comment by SuperHero2010** [comment]
You're the one who doesn't understand what I'm saying.

**Comment by SuperHero2010** [comment]
Don't disturb me. I'm busy.

**Comment by SuperHero2010** [comment]
I understand. But you're the one who doesn't understand what I'm saying. I am learning "Python" so I am busy. Please don't disturb me.
